# Generated by scripts/homebrew/formula.ts in cubeyard/cube from the signed
# darwin-arm64 manifest of release v0.3.18 (cube-runner 0.8.4). Do not edit by hand.
class CubeRunner < Formula
  desc "Cube's VM runner: one QEMU machine per coding-agent thread"
  homepage "https://github.com/cubeyard/cube"
  url "https://github.com/cubeyard/cube/releases/download/v0.3.18/cube-runner-v0.3.18-darwin-arm64.tar.gz"
  sha256 "aafbd36185b95c9e2cd72f93351d433c46d695fd0d7ec35eeb290ec0b0d1bee3"
  license "Apache-2.0"

  depends_on arch: :arm64
  depends_on :macos
  depends_on "qemu"

  def install
    bin.install "bin/cube-runner"
    # The operator scripts and the pinned release key, for reference; the
    # self-updater they implement is not installed: brew upgrade updates
    # this runner.
    libexec.install "scripts", "update-public-key.pem", "MANIFEST"
    # The service's entry point: the home is resolved when the service
    # starts, for the user who starts it.
    (libexec/"service.sh").write <<~SH
      #!/bin/sh
      set -eu
      exec "#{opt_bin}/cube-runner" run --home "${CUBE_RUNNER_HOME:-$HOME/.cube/runner}" "$@"
    SH
    chmod 0755, libexec/"service.sh"
  end

  # The local runner that `cubed runners init-local` sets up under
  # ~/.cube/runner (its default --home). It runs as the user who starts the
  # service: the thread machines are sandboxes, QEMU itself is not. SIGTERM
  # powers the machines down (up to 30 s each) before the runner exits.
  service do
    run [opt_libexec/"service.sh"]
    keep_alive true
    stop_timeout 60
    log_path var/"log/cube-runner.log"
    error_log_path var/"log/cube-runner.log"
    environment_variables PATH: std_service_path_env
  end

  def caveats
    <<~EOS
      The runner needs Hypervisor.framework and a Debian 13 genericcloud arm64 image.
      Set it up from the cube formula with:
        cubed runners init-local --image /path/to/debian-13-genericcloud-arm64.qcow2
      then: brew services start cube-runner
      After brew upgrade: brew services restart cube-runner (a running service is not restarted).
      Its state (key, base image, machine disks) is ~/.cube; uninstalling keeps it.
      QEMU runs as your user; a thread's machine is the sandbox, this Mac is not.
    EOS
  end

  test do
    assert_match '"protocolVersion":3', shell_output("#{bin}/cube-runner version")
    assert_match "cube-runner init", shell_output("#{bin}/cube-runner --help")
    assert_predicate libexec/"service.sh", :executable?
  end
end
