# Generated by scripts/homebrew/formula.ts in cubeyard/cube from the signed
# darwin-arm64 manifest of release v0.3.22. Do not edit by hand.
class Cube < Formula
  desc "Self-hosted durable coding-agent threads, each in its own virtual machine"
  homepage "https://github.com/cubeyard/cube"
  url "https://github.com/cubeyard/cube/releases/download/v0.3.22/cubed-v0.3.22-darwin-arm64.tar.gz"
  sha256 "eea6873141f54a2e10738b344d35e3f7f78e59ac9163ab1a0b288e58bfdd355d"
  license "Apache-2.0"

  depends_on arch: :arm64
  depends_on "cubeyard/tap/cube-runner"
  depends_on "gh"
  depends_on :macos

  def install
    # The signed bundle as released: bin/node, bin/cube-gateway, app/,
    # release.json (cubed finds its gateway next to release.json).
    libexec.install Dir["*"]
    # A dependency (pi-tui) ships prebuilt native modules for every platform;
    # only this one's may stay in the keg (brew audit refuses the others).
    # They live under node_modules/.pnpm, so the glob must match dot directories.
    Dir.glob(libexec/"app/**/native/*/prebuilds/*", File::FNM_DOTMATCH).each do |dir|
      name = File.basename(dir)
      next if !File.directory?(dir) || (name.start_with?("darwin-") && name.include?("arm64"))

      rm_r(dir)
    end
    # The bundle's bin/cubed starts the self-update supervisor; under
    # Homebrew, cubed runs directly and brew upgrade updates it.
    (bin/"cubed").write <<~SH
      #!/bin/sh
      set -eu
      config="${CUBED_CONFIG_FILE:-$HOME/.config/cubed/environment}"
      if [ -f "$config" ]; then
        set -a
        # shellcheck source=/dev/null
        . "$config"
        set +a
      fi
      # Threads' `cube service` URLs work in a browser on this Mac out of
      # the box: the portal on loopback, under *.localhost names browsers
      # resolve themselves (no DNS). Any CUBED_PORTAL_IP, _LISTEN or _DOMAIN
      # of the operator's is kept as it is; CUBED_PORTAL_IP= turns it off.
      if [ -z "${CUBED_PORTAL_IP+set}${CUBED_PORTAL_LISTEN+set}${CUBED_PORTAL_DOMAIN+set}" ]; then
        export CUBED_PORTAL_IP=127.0.0.1 CUBED_PORTAL_DOMAIN=localhost
      fi
      export CUBE_RUNNER="${CUBE_RUNNER:-#{HOMEBREW_PREFIX}/opt/cube-runner/bin/cube-runner}"
      export CUBED_VERSION="v0.3.22" CUBED_COMMIT="1dd8dc79f40f4d5d75794e87b62b63bfff2c2c04"
      exec "#{libexec}/bin/node" "#{libexec}/app/packages/server/src/index.ts" "$@"
    SH
    chmod 0755, bin/"cubed"
  end

  service do
    run [opt_bin/"cubed"]
    keep_alive true
    stop_timeout 60
    log_path var/"log/cubed.log"
    error_log_path var/"log/cubed.log"
    environment_variables PATH: std_service_path_env
  end

  def caveats
    <<~EOS
      One-time setup on this Mac (Apple Silicon); the first command downloads
      Debian's genericcloud arm64 image (~340 MB, checksum-verified):
        cubed runners init-local
        brew services start cube-runner
        brew services start cube
      Then open http://127.0.0.1:7777, connect a model under "models" and run
      "gh auth login" for GitHub. cubed listens on loopback only and has no user
      authentication; keep it there or behind an authenticated private network.
      Settings go in ~/.config/cubed/environment (CUBED_STATE, CUBED_HOST,
      CUBED_ALLOWED_HOSTS, CUBED_CLAUDE, ...). Web servers a thread runs with
      "cube service" get URLs like http://web-<label>.localhost:7780/ that
      open only in a browser on this Mac (loopback). CUBED_PORTAL_IP= turns
      them off; CUBED_PORTAL_IP=<this Mac's Tailscale IPv4> serves them to your
      tailnet instead (docs/services.md). State: ~/.cube-host and ~/.cube;
      uninstalling keeps both. After brew upgrade, restart the services:
        brew services restart cube-runner cube
      Had this tap's old v0.1 "cube" launcher? Its VM may still run and hold
      port 7777: check ps -p "$(cat ~/.cube/vm.pid)" -o command= for qemu, kill
      that pid, and move ~/.cube aside before init-local.
    EOS
  end

  test do
    assert_match "cubed", shell_output("#{bin}/cubed --version")
    assert_match "runners status", shell_output("#{bin}/cubed --help")
    check = JSON.parse(shell_output("#{bin}/cubed --self-check"))
    assert_equal "v0.3.22", check["version"]
    assert_match(/^cube-gateway /, check["gateway"])
  end
end
